# Generated by Django 6.0.3 on 2026-06-27 06:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('jurisdiction', models.CharField(default='Nigeria', max_length=80)),
                ('tax_type', models.CharField(choices=[('vat', 'Value Added Tax'), ('cit', 'Company Income Tax')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('threshold_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('threshold_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tax_type', 'threshold_min', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='TaxEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('rule_snapshot', models.JSONField(default=dict)),
                ('assumptions', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
