# Generated by Django 6.0.3 on 2026-06-27 16:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('moving_average_trend', 'Moving average with trend adjustment')], default='moving_average_trend', max_length=40)),
                ('lookback_days', models.PositiveIntegerField(default=30)),
                ('horizon_days', models.PositiveIntegerField(default=14)),
                ('period_granularity', models.CharField(choices=[('daily', 'Daily')], default='daily', max_length=20)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('assumptions', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('projected_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('projected_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('projected_gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('projected_net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('projected_cash_position', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('projected_inventory_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('forecast_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='forecasting.forecastrun')),
            ],
            options={
                'ordering': ['period_start', 'id'],
            },
        ),
    ]
